// Route inventory data (chunk 2/7). Order is load-bearing.
import { route } from './_shared.js';

export const part2 = [
  route({
    method: 'POST',
    route: '/api/auth/pairing-codes',
    group: 'auth',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'paired authorized session required',
    validation: 'actor spoofing rejected; short-lived one-time code generated server-side',
    auditEvent: 'auth_pairing_code_created',
    uiSurface: 'settings/auth',
    smokeCoverage: ['test/server.test.js', 'test/auth-sessions.test.js'],
    serverHints: ["parts[2] === 'pairing-codes'"],
  }),
  route({
    method: 'POST',
    route: '/api/auth/pair',
    group: 'auth',
    auth: 'one_time_pairing_code',
    mutationRisk: 'medium',
    approval: 'valid unexpired single-use pairing code',
    validation: 'actor spoofing rejected; code consumed once; HttpOnly SameSite cookie issued',
    auditEvent: 'auth_browser_session_created',
    uiSurface: 'settings/auth',
    smokeCoverage: ['test/server.test.js', 'test/auth-sessions.test.js'],
    serverHints: ["parts[2] === 'pair'"],
  }),
  route({
    method: 'GET',
    route: '/api/auth/sessions',
    group: 'auth',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'authorized session required',
    validation: 'lists redacted browser sessions only',
    auditEvent: 'none',
    uiSurface: 'settings/auth',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[2] === 'sessions'"],
  }),
  route({
    method: 'POST',
    route: '/api/auth/logout',
    group: 'auth',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized session required',
    validation: 'actor spoofing rejected; revokes cookie token or requested session id',
    auditEvent: 'auth_browser_session_revoked',
    uiSurface: 'settings/auth',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[2] === 'logout'"],
  }),

  route({
    method: 'GET',
    route: '/api/agent-tools/discovery',
    group: 'agent-tools',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'public-safe tool metadata only',
    auditEvent: 'none',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/agent-tools.test.js', 'test/server.test.js'],
    serverHints: ["parts[1] === 'agent-tools'", "parts[2] === 'discovery'"],
  }),
  route({
    method: 'GET',
    route: '/api/agent-tools/next-action',
    group: 'agent-tools',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'query decoding; role/project/session/lane lookup',
    auditEvent: 'none',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/agent-tools.test.js', 'test/server.test.js'],
    serverHints: ["parts[2] === 'next-action'"],
  }),
  route({
    method: 'POST',
    route: '/api/agent-tools/leases',
    group: 'agent-tools',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; lease binds role/project/session/lane/allowedTools/ttl',
    auditEvent: 'tool_lease_created',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/agent-tools.test.js', 'test/server.test.js'],
    serverHints: ["parts[2] === 'leases'"],
  }),
  route({
    method: 'GET',
    route: '/api/agent-tools/leases',
    group: 'agent-tools',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'read-only; returns hashed-token-free public lease records (no raw tokens)',
    auditEvent: 'none',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['activeOnly'],
  }),
  route({
    method: 'DELETE',
    route: '/api/agent-tools/leases/{leaseId}',
    group: 'agent-tools',
    auth: 'api_token_or_local_host_admin',
    mutationRisk: 'high',
    approval: 'admin-gated (host API token or local host admin)',
    validation: 'admin auth required; lease id exists; idempotent on already-revoked',
    auditEvent: 'agent_tool_lease_revoked',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['revokeToolLease'],
  }),

  route({
    method: 'GET',
    route: '/api/private-access',
    group: 'private-access',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'fakeTailnetState query decoded; no real Tailscale mutation',
    auditEvent: 'none',
    uiSurface: 'private access settings',
    smokeCoverage: ['test/server.test.js', 'smoke:private-access'],
    serverHints: ["parts[1] === 'private-access'", 'handlePrivateAccessApi'],
  }),
  route({
    method: 'GET',
    route: '/api/private-access/tailnet',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'fake state query decoded',
    auditEvent: 'none',
    uiSurface: 'private access settings',
    smokeCoverage: ['test/server.test.js', 'smoke:private-access', 'smoke:ssrf'],
    serverHints: ["parts[2] === 'tailnet'"],
  }),
  route({
    method: 'GET',
    route: '/api/private-access/setup-plan',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'local URL/port validation; dry-run commands only; Funnel rejected',
    auditEvent: 'none',
    uiSurface: 'private access settings',
    smokeCoverage: ['test/server.test.js', 'smoke:private-access', 'smoke:ssrf'],
    serverHints: ["parts[2] === 'setup-plan'"],
  }),
  route({
    method: 'POST',
    route: '/api/private-access/serve',
    group: 'private-access',
    auth: 'api_token_or_local_host_admin',
    mutationRisk: 'high',
    approval: 'admin-only host network exposure',
    validation: 'actor spoofing rejected; action clamped to enable/disable; port defaulted',
    auditEvent: 'tailscale_serve_configured',
    uiSurface: 'private access settings',
    smokeCoverage: ['smoke:private-access'],
    serverHints: ["parts[2] === 'serve'"],
  }),
  route({
    method: 'PATCH',
    route: '/api/private-access/settings',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; URL mode policy validation',
    auditEvent: 'private_access_settings_updated',
    uiSurface: 'private access settings',
    smokeCoverage: ['smoke:private-access'],
    serverHints: ["parts[2] === 'settings'"],
  }),
  route({
    method: 'POST',
    route: '/api/private-access/targets',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; local/tailnet URL validation; Funnel rejected',
    auditEvent: 'private_access_target_created',
    uiSurface: 'private access settings',
    smokeCoverage: ['test/server.test.js', 'smoke:private-access'],
    serverHints: ["parts[2] === 'targets'", 'createTarget'],
  }),
  route({
    method: 'PATCH',
    route: '/api/private-access/targets/{targetId}',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; target exists; URL validation; Funnel rejected',
    auditEvent: 'private_access_target_updated',
    uiSurface: 'private access settings',
    smokeCoverage: ['smoke:private-access'],
    serverHints: ['updateTarget'],
  }),
  route({
    method: 'DELETE',
    route: '/api/private-access/targets/{targetId}',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; target exists',
    auditEvent: 'private_access_target_deleted',
    uiSurface: 'private access settings',
    smokeCoverage: ['smoke:private-access'],
    serverHints: ['deleteTarget'],
  }),
  route({
    method: 'POST',
    route: '/api/private-access/targets/{targetId}/check',
    group: 'private-access',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; target exists; health check is dry-run/local-safe',
    auditEvent: 'private_access_target_checked',
    uiSurface: 'private access settings',
    smokeCoverage: ['smoke:private-access'],
    serverHints: ['checkTarget'],
  }),

  route({
    method: 'GET',
    route: '/api/providers',
    group: 'providers',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'secret values redacted',
    auditEvent: 'none',
    uiSurface: 'providers/settings',
    smokeCoverage: ['test/provider-profiles.test.js', 'test/server.test.js', 'smoke:providers'],
    serverHints: ["parts[1] === 'providers'", 'listProfiles'],
  }),
  route({
    method: 'GET',
    route: '/api/providers/export',
    group: 'providers',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'schema-versioned export; excludes secret values',
    auditEvent: 'none',
    uiSurface: 'providers/import-export',
    smokeCoverage: ['test/provider-profiles.test.js', 'test/server.test.js'],
    serverHints: ['exportProfiles'],
  }),
  route({
    method: 'POST',
    route: '/api/providers/import/dry-run',
    group: 'providers',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; schema validation; secret values/prototype pollution rejected',
    auditEvent: 'provider_import_dry_run',
    uiSurface: 'providers/import-export',
    smokeCoverage: ['test/provider-profiles.test.js'],
    serverHints: ['importDryRun'],
  }),
];
