// Route inventory data (chunk 1/7). Order is load-bearing.
import { route, centralRateLimit } from './_shared.js';

export const part1 = [
  route({
    method: 'GET',
    route: '/api/health',
    group: 'system',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'none',
    auditEvent: 'none',
    uiSurface: 'system health',
    smokeCoverage: ['smoke:api', 'test/server.test.js'],
    serverHints: ["parts[1] === 'health'"],
  }),
  route({
    method: 'GET',
    route: '/api/policy',
    group: 'system',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'none',
    auditEvent: 'none',
    uiSurface: 'settings/policy',
    smokeCoverage: ['smoke:api'],
    serverHints: ["parts[1] === 'policy'"],
  }),
  route({
    method: 'GET',
    route: '/api/settings/effective',
    group: 'settings',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'project/session/lane query lookup; secret-free effective policy only',
    auditEvent: 'none',
    uiSurface: 'settings/effective policy',
    smokeCoverage: ['test/effective-settings.test.js', 'test/effective-settings-api.test.js', 'smoke:route-inventory'],
    mobileBehavior: 'available to phone dashboard; no secret values returned',
    serverHints: ["parts[1] === 'settings'", "parts[2] === 'effective'", 'getEffectiveSettings'],
  }),
  route({
    method: 'PATCH',
    route: '/api/settings/{scope}/{id}',
    group: 'settings',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'updateProject policy approval',
    validation: 'scope allowlist project/session/lane; actor spoofing rejected; schema validation; prototype-pollution rejected; no secret fields',
    auditEvent: 'settings_overrides_updated',
    uiSurface: 'settings/effective policy',
    smokeCoverage: ['test/effective-settings.test.js', 'test/effective-settings-api.test.js', 'smoke:route-inventory'],
    mobileBehavior: 'settings changes available from phone after auth; disabled/blocked errors explain approval needs',
    serverHints: ["parts[1] === 'settings'", 'updateSettingsOverrides'],
  }),
  route({
    method: 'GET',
    route: '/api/notifications',
    group: 'notifications',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'limit/unread query decoded; secret-redacted notification payloads only',
    auditEvent: 'none',
    uiSurface: 'notifications/settings',
    smokeCoverage: ['test/server.test.js', 'smoke:notifications', 'smoke:route-inventory'],
    mobileBehavior: 'available to phone dashboard with secret-free short status and safe links',
    serverHints: ["parts[1] === 'notifications'", 'getNotifications'],
  }),
  route({
    method: 'PATCH',
    route: '/api/notifications/settings',
    group: 'notifications',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'manageNotifications',
    validation: 'actor spoofing rejected; severity allowlist; booleans normalized',
    auditEvent: 'notification_settings_updated',
    uiSurface: 'notifications/settings',
    smokeCoverage: ['test/server.test.js', 'smoke:notifications'],
    mobileBehavior: 'phone can configure in-app/browser notification behavior after auth',
    serverHints: ["parts[1] === 'notifications'", 'updateNotificationSettings'],
  }),
  route({
    method: 'POST',
    route: '/api/notifications/{notificationId}/read',
    group: 'notifications',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; notification exists; idempotent read state',
    auditEvent: 'none_low_risk_read_state',
    uiSurface: 'notifications/settings',
    smokeCoverage: ['test/server.test.js', 'smoke:notifications'],
    mobileBehavior: 'phone can mark individual notifications read after auth',
    serverHints: ['markNotificationRead'],
  }),
  route({
    method: 'POST',
    route: '/api/notifications/read-all',
    group: 'notifications',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; idempotent bulk read state',
    auditEvent: 'none_low_risk_read_state',
    uiSurface: 'notifications/settings',
    smokeCoverage: ['test/server.test.js', 'smoke:notifications'],
    mobileBehavior: 'phone can clear notification unread state after auth',
    serverHints: ['markAllNotificationsRead'],
  }),
  route({
    method: 'GET',
    route: '/api/app/export',
    group: 'app-backup',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'secret/auth/artifact exclusion; local-only app backup schema',
    auditEvent: 'none_sensitive_read',
    bodyLimit: 'none',
    uiSurface: 'settings/import-export-support',
    smokeCoverage: ['test/app-backup.test.js', 'smoke:app-backup'],
    mobileBehavior: 'phone can download/copy a local-only backup after auth; no secrets included',
    serverHints: ["parts[1] === 'app'", 'buildAppExport'],
  }),
  route({
    method: 'POST',
    route: '/api/app/import/dry-run',
    group: 'app-backup',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized dashboard/session context',
    validation: 'actor spoofing rejected; schema validation; secret/auth/artifact fields rejected; non-destructive summary only',
    auditEvent: 'none_dry_run',
    uiSurface: 'settings/import-export-support',
    smokeCoverage: ['test/app-backup.test.js', 'smoke:app-backup'],
    mobileBehavior: 'phone can validate backup before apply after auth',
    serverHints: ['validateAppImport'],
  }),
  route({
    method: 'POST',
    route: '/api/app/import/apply',
    group: 'app-backup',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'critical',
    approval: 'manageAppBackups',
    validation: 'actor spoofing rejected; explicit approval; schema validation; merge-only non-destructive apply; active lanes imported as stopped',
    auditEvent: 'app_import_applied',
    uiSurface: 'settings/import-export-support',
    smokeCoverage: ['test/app-backup.test.js', 'smoke:app-backup'],
    mobileBehavior: 'phone can apply a validated backup after auth and explicit approval',
    serverHints: ['applyAppImport'],
  }),
  route({
    method: 'GET',
    route: '/api/app/support-bundle',
    group: 'app-backup',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'authorized dashboard/session context',
    validation: 'redacted support schema; no auth sessions, secrets, artifacts, screenshots, videos, or traces',
    auditEvent: 'none_sensitive_read',
    bodyLimit: 'none',
    uiSurface: 'settings/import-export-support',
    smokeCoverage: ['test/app-backup.test.js', 'smoke:app-backup'],
    mobileBehavior: 'phone can copy/share support diagnostics after auth; redacted by default',
    serverHints: ['buildSupportBundle'],
  }),
  route({
    method: 'GET',
    route: '/api/route-inventory',
    group: 'system',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'public-safe route metadata only',
    auditEvent: 'none',
    uiSurface: 'system health/blockers',
    smokeCoverage: ['smoke:route-inventory'],
    serverHints: ["parts[1] === 'route-inventory'"],
  }),
  route({
    method: 'GET',
    route: '/api/streams/events',
    group: 'streams',
    auth: 'api_token_or_paired_browser_session_when_token_configured',
    mutationRisk: 'none',
    approval: 'authorized stream context when token configured',
    validation: 'same-origin paired browser session or API token; compact SSE payload; closes on auth revocation',
    auditEvent: 'none',
    bodyLimit: 'none',
    rateLimit: centralRateLimit,
    uiSurface: 'dashboard live updates',
    smokeCoverage: ['smoke:streams', 'test/streams.test.js'],
    mobileBehavior: 'available to phone/PWA dashboard with paired browser session; no tokens in URL',
    serverHints: ["parts[1] === 'streams'", "parts[2] === 'events'", 'handleEventStream'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/stream',
    group: 'streams',
    auth: 'api_token_or_paired_browser_session_or_scoped_lane_get_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized lane stream context; tool leases must grant lane.get for the lane',
    validation: 'lane exists; operator auth may stream any lane; scoped tool lease must validate lane.get against the lane project/session/id; pushes bounded terminal.log snapshots and append events',
    auditEvent: 'none',
    bodyLimit: 'none',
    rateLimit: centralRateLimit,
    uiSurface: 'lane detail live terminal output',
    smokeCoverage: ['smoke:lane-stream', 'test/streams.test.js'],
    mobileBehavior: 'available to paired dashboard views and scoped MCP supervisors/orchestrators that hold lane.get; no tokens in URL',
    serverHints: ["parts[1] === 'lanes'", "parts[3] === 'stream'", 'handleLaneStream', 'hasLaneStreamAuth'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/terminal-tail',
    group: 'streams',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized lane terminal context; tool leases must grant lane.terminal.tail for the lane',
    validation: 'lane exists; bounded terminal.log tail only; offset/maxBytes query clamped; scoped tool lease must validate lane.terminal.tail against the lane project/session/id',
    auditEvent: 'none',
    bodyLimit: 'none',
    rateLimit: centralRateLimit,
    uiSurface: 'MCP agent live worker output',
    smokeCoverage: ['test/streams.test.js', 'test/mcp-dogfood-flow.test.js'],
    mobileBehavior: 'available to scoped MCP supervisors/orchestrators for near-live worker output without opening SSE',
    serverHints: ["parts[1] === 'lanes'", "parts[3] === 'terminal-tail'", 'lane.terminal.tail'],
  }),
  route({
    method: 'GET',
    route: '/api/system/blockers',
    group: 'system',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'blocker shape only',
    auditEvent: 'none',
    uiSurface: 'system health',
    smokeCoverage: ['test/registry.test.js', 'smoke:ui'],
    serverHints: ["parts[1] === 'system'", "parts[2] === 'blockers'"],
  }),
  route({
    method: 'GET',
    route: '/api/system/dirs',
    group: 'system',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'workstation directory picker; jailed to approved repo roots (ORCA_REPO_ROOTS); dirs only, no file contents; traversal + symlink escape refused',
    auditEvent: 'none',
    uiSurface: 'project/session workstation directory picker',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[2] === 'dirs'", 'listWorkstationDirs'],
  }),
  route({
    method: 'GET',
    route: '/api/archive',
    group: 'system',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'read-only list of archived projects + sessions for the Settings archive view; no secrets',
    auditEvent: 'none',
    uiSurface: 'settings archive (restore)',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[1] === 'archive'", 'listArchived'],
  }),
  route({
    method: 'GET',
    route: '/api/mobile/manifest',
    group: 'mobile',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'origin-derived links only',
    auditEvent: 'none',
    uiSurface: 'phone setup/mobile manifest',
    smokeCoverage: ['test/server.test.js', 'smoke:api'],
    serverHints: ["parts[1] === 'mobile'", "parts[2] === 'manifest'"],
  }),

  route({
    method: 'GET',
    route: '/api/auth/status',
    group: 'auth',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'cookie and API token status only, no secret echo',
    auditEvent: 'none',
    uiSurface: 'settings/auth',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[1] === 'auth'", "parts[2] === 'status'"],
  }),
];
