// Route inventory data (chunk 6/7). Order is load-bearing.
import { route } from './_shared.js';

export const part6 = [
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/critique/findings',
    group: 'critique',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized executor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; current nonce; visual-required fresh screenshot',
    auditEvent: 'critique_findings_recorded',
    uiSurface: 'critique/self-check detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['recordCritiqueFindings'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/critique/waive',
    group: 'critique',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'waiveCritique',
    validation: 'actor spoofing rejected; reason required; policy approval',
    auditEvent: 'critique_waived',
    uiSurface: 'critique/self-check detail',
    smokeCoverage: ['test/critique-audit.test.js'],
    serverHints: ['waiveCritique'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/audit/accept',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized auditor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; critique satisfied; lane accepted once',
    auditEvent: 'lane_audit_accepted',
    uiSurface: 'audit detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['acceptLaneAudit'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/audit/findings',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized auditor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; verdict accepted/fix_requested/blocked',
    auditEvent: 'lane_audit_accepted_or_fix_requested_or_blocked',
    uiSurface: 'audit detail',
    smokeCoverage: ['test/critique-audit-api.test.js'],
    serverHints: ['requestLaneFix', 'blockLaneAudit'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/audit/request-fix',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized auditor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; next task/findings recorded',
    auditEvent: 'lane_audit_fix_requested',
    uiSurface: 'audit detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['requestLaneFix'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/audit/block',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized auditor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; reason required',
    auditEvent: 'lane_audit_blocked',
    uiSurface: 'audit detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['blockLaneAudit'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/audit-events',
    group: 'audit',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'lane exists; status query decoded',
    auditEvent: 'none',
    uiSurface: 'lane detail/audit queue',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[3] === 'audit-events'"],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/heartbeat',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session_plus_optional_worker_token',
    mutationRisk: 'high_frequency_medium',
    approval: 'worker token if configured',
    validation: 'lane exists; optional ORCA_WORKER_TOKEN; actor spoofing rejected',
    auditEvent: 'none_high_frequency_state_update',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['touchHeartbeat'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/submit',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'lane in submittable state; actor spoofing rejected; summary/changedFiles bounded',
    auditEvent: 'lane_submitted',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['submitLane'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/approvals',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'lane exists',
    auditEvent: 'none',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['getLaneApprovals'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/approvals',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'lane exists; actor spoofing rejected; kind/detail bounded',
    auditEvent: 'lane_approval_requested',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['recordLaneApproval'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/approvals/{approvalId}/decide',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'approval exists and pending; decision approve|deny; actor spoofing rejected',
    auditEvent: 'lane_approval_decided',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['decideLaneApproval'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/artifacts',
    group: 'evidence',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'lane exists; artifact path containment',
    auditEvent: 'none',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['smoke:api'],
    serverHints: ['listArtifactFiles'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/evidence',
    group: 'evidence',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped evidence.list tool lease',
    validation: 'lane exists; evidence file filter; scoped tool leases must validate against the lane project/session/id',
    auditEvent: 'none',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['smoke:api'],
    serverHints: ["parts[3] === 'evidence'"],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/evidence',
    group: 'evidence',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'captureEvidence',
    validation: 'actor spoofing rejected; presetId resolved server-side; URL/mode allowlists; SSRF policy in evidence capture',
    auditEvent: 'lane_evidence_captured_or_failed',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['smoke:api', 'test/server.test.js', 'smoke:ssrf'],
    serverHints: ['captureLaneEvidence'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/evidence/latest',
    group: 'evidence',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped evidence.latest tool lease',
    validation: 'lane exists; mode query decoded; scoped tool leases must validate against the lane project/session/id',
    auditEvent: 'none',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['smoke:api'],
    serverHints: ['getLatestEvidence'],
  }),
  route({
    method: 'GET',
    route: '/api/lanes/{laneId}/evidence/presets',
    group: 'evidence',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'lane exists',
    auditEvent: 'none',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['smoke:api'],
    serverHints: ['getEvidencePresets'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/evidence/clear',
    group: 'evidence',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'clearEvidenceArtifacts',
    validation: 'actor spoofing rejected; lane exists; artifact path containment',
    auditEvent: 'lane_evidence_cleared',
    uiSurface: 'evidence gallery/lane detail',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['clearLaneEvidenceArtifacts'],
  }),
];
