// Route inventory data (chunk 4/7). Order is load-bearing.
import { route } from './_shared.js';

export const part4 = [
  route({
    method: 'POST',
    route: '/api/mcp/tools',
    group: 'mcp',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageMcpTools',
    validation: 'actor spoofing rejected; command/args/env/workdir/scope allowlists',
    auditEvent: 'mcp_tool_created',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/registry.test.js', 'test/server.test.js'],
    serverHints: ['createMcpTool'],
  }),
  route({
    method: 'POST',
    route: '/api/mcp/orchestrator-bootstrap',
    group: 'mcp',
    // Mints an off-origin host credential (orchestrator lease) — requires ADMIN
    // (requireAdminAuth in src/server-routes/mcp.js). Paired phones are rejected.
    auth: 'api_token_or_local_host_admin',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'actor spoofing rejected; project/session existence + relationship; ttl clamped',
    auditEvent: 'orchestrator_mcp_bootstrap_created',
    uiSurface: 'pair/desktop-control',
    smokeCoverage: ['test/mcp-orchestrator-bootstrap.test.js', 'test/server.test.js'],
    serverHints: ['createOrchestratorMcpBootstrap'],
  }),
  route({
    method: 'POST',
    route: '/api/mcp/supervisor-bootstrap',
    group: 'mcp',
    auth: 'api_token_or_local_host_admin',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'actor spoofing rejected; ttl clamped; mints scoped supervisor lease',
    auditEvent: 'supervisor_mcp_bootstrap_created',
    uiSurface: 'desktop-control/supervisor',
    smokeCoverage: ['test/mcp-orchestrator-bootstrap.test.js'],
    serverHints: ['createOrchestratorMcpBootstrap'],
  }),
  route({
    method: 'GET',
    route: '/api/mcp/tools/{toolId}',
    group: 'mcp',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'tool exists',
    auditEvent: 'none',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['getMcpTools'],
  }),
  route({
    method: 'PATCH',
    route: '/api/mcp/tools/{toolId}',
    group: 'mcp',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageMcpTools',
    validation: 'actor spoofing rejected; command/args/env/workdir/scope allowlists',
    auditEvent: 'mcp_tool_updated',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/registry.test.js', 'test/server.test.js'],
    serverHints: ['updateMcpTool'],
  }),
  route({
    method: 'DELETE',
    route: '/api/mcp/tools/{toolId}',
    group: 'mcp',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageMcpTools',
    validation: 'actor spoofing rejected; tool exists; detach from lane snapshots',
    auditEvent: 'mcp_tool_deleted',
    uiSurface: 'MCP/tools',
    smokeCoverage: ['test/registry.test.js', 'test/server.test.js'],
    serverHints: ['deleteMcpTool'],
  }),

  route({
    method: 'GET',
    route: '/api/projects',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped project.list tool lease',
    validation: 'scoped tool leases are filtered to the lease project/session/lane project',
    auditEvent: 'none',
    uiSurface: 'project rail/home',
    smokeCoverage: ['smoke:api', 'smoke:ui-inventory'],
    serverHints: ["parts[1] === 'projects'"],
  }),
  route({
    method: 'POST',
    route: '/api/projects',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'createProject',
    validation: 'actor spoofing rejected; project name/slug validation',
    auditEvent: 'project_created',
    uiSurface: 'project creation',
    smokeCoverage: ['test/server.test.js', 'smoke:api'],
    serverHints: ['createProject'],
  }),
  route({
    method: 'GET',
    route: '/api/projects/{projectId}',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped project.describe tool lease',
    validation: 'project exists; scoped tool leases must validate against the project id',
    auditEvent: 'none',
    uiSurface: 'project detail',
    smokeCoverage: ['smoke:ui-inventory'],
    serverHints: ['getProject'],
  }),
  route({
    method: 'PATCH',
    route: '/api/projects/{projectId}',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'updateProject',
    validation: 'actor spoofing rejected; quick links validated',
    auditEvent: 'project_updated',
    uiSurface: 'quick links/project URLs',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['updateProject'],
  }),
  route({
    method: 'POST',
    route: '/api/projects/{projectId}/archive',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'high',
    approval: 'updateProject',
    validation: 'actor spoofing rejected; project exists; sets state archived through updateProject policy',
    auditEvent: 'project_updated',
    uiSurface: 'project archive/settings',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['updateProject'],
  }),
  route({
    method: 'POST',
    route: '/api/projects/{projectId}/restore',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'high',
    approval: 'updateProject',
    validation: 'actor spoofing rejected; project exists; sets state active through updateProject policy',
    auditEvent: 'project_updated',
    uiSurface: 'settings archive (restore)',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['updateProject'],
  }),
  route({
    method: 'POST',
    route: '/api/projects/{projectId}/quick-links',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'high',
    approval: 'authorized operator or scoped project.quick_link.upsert tool lease',
    validation: 'actor spoofing rejected; scoped tool leases must validate against the project id; URL/port/kind fields validated; SSRF policy reused',
    auditEvent: 'project_quick_link_upserted',
    uiSurface: 'quick links/project URLs',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['upsertProjectQuickLink'],
  }),
  route({
    method: 'PATCH',
    route: '/api/projects/{projectId}/quick-links/{linkId}',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'updateProject',
    validation: 'actor spoofing rejected; quick link exists; URL/port/kind fields validated; SSRF policy reused',
    auditEvent: 'project_quick_link_upserted',
    uiSurface: 'quick links/project URLs',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['upsertProjectQuickLink'],
  }),
  route({
    method: 'DELETE',
    route: '/api/projects/{projectId}/quick-links/{linkId}',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'high',
    approval: 'authorized operator or scoped project.quick_link.delete tool lease',
    validation: 'actor spoofing rejected; scoped tool leases must validate against the project id; quick link exists',
    auditEvent: 'project_quick_link_deleted',
    uiSurface: 'quick links/project URLs',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['deleteProjectQuickLink'],
  }),
  route({
    method: 'POST',
    route: '/api/projects/{projectId}/quick-links/{linkId}/check',
    group: 'projects',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'medium',
    approval: 'authorized operator or scoped project.quick_link.health tool lease',
    validation: 'actor spoofing rejected; scoped tool leases must validate against the project id; quick link exists; health check uses validated quick-link URL plus relative healthPath only',
    auditEvent: 'project_quick_link_health_checked',
    uiSurface: 'quick links/project URLs',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['checkProjectQuickLink'],
  }),
  route({
    method: 'GET',
    route: '/api/projects/{projectId}/sessions',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped session.list tool lease',
    validation: 'project exists; scoped tool leases must validate against the project id',
    auditEvent: 'none',
    uiSurface: 'project detail',
    smokeCoverage: ['smoke:api', 'smoke:ui-inventory'],
    serverHints: ['listSessions'],
  }),
  route({
    method: 'POST',
    route: '/api/projects/{projectId}/sessions',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'high',
    approval: 'authorized operator or scoped session.create tool lease',
    validation: 'actor spoofing rejected; scoped tool leases must validate against the project id; name/repoRoot/capacity policy validation',
    auditEvent: 'session_created',
    uiSurface: 'project detail/session create',
    smokeCoverage: ['test/server.test.js', 'smoke:api'],
    serverHints: ['createSession'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped session.describe tool lease',
    validation: 'session exists; scoped tool leases must validate against the session project/id',
    auditEvent: 'none',
    uiSurface: 'session/workflow',
    smokeCoverage: ['smoke:ui-inventory'],
    serverHints: ["parts[1] === 'sessions'"],
  }),
  route({
    method: 'PATCH',
    route: '/api/sessions/{sessionId}',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'updateSession',
    validation: 'actor spoofing rejected; state quick edit/patch validation',
    auditEvent: 'session_updated',
    uiSurface: 'session/workflow',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['updateSession'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/capacity',
    group: 'capacity',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'session exists',
    auditEvent: 'none',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/server.test.js'],
    serverHints: ['getSessionCapacity'],
  }),
];
