// Route inventory data (chunk 7/7). Order is load-bearing.
import { route } from './_shared.js';

export const part7 = [
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/worktree/remove',
    group: 'cleanup',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'critical',
    approval: 'cleanupArtifacts',
    validation: 'actor spoofing rejected; terminal lane; managed worktree containment; shared/non-managed worktrees refused',
    auditEvent: 'lane_worktree_removed',
    uiSurface: 'lane detail/cleanup',
    smokeCoverage: ['test/registry.test.js', 'smoke:api'],
    serverHints: ['removeLaneWorktree'],
  }),

  route({
    method: 'GET',
    route: '/artifacts/{sessionId}/{laneId}/{file}',
    group: 'static-artifacts',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'lane exists; path traversal/absolute/encoded/symlink refused',
    auditEvent: 'none',
    uiSurface: 'evidence gallery/artifacts',
    smokeCoverage: ['test/server.test.js', 'smoke:api'],
    serverHints: ["pathname.startsWith('/artifacts/')"],
  }),
  route({
    method: 'GET',
    route: '/',
    group: 'static-app',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'static dir path containment',
    auditEvent: 'none',
    uiSurface: 'app shell',
    smokeCoverage: ['smoke:ui', 'smoke:ui-inventory', 'smoke:ui-contract'],
    serverHints: ['serveStaticOrIndex'],
  }),
  route({
    method: 'GET',
    route: '/styles.css',
    group: 'static-app',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'static dir path containment',
    auditEvent: 'none',
    uiSurface: 'app shell',
    smokeCoverage: ['smoke:ui', 'smoke:ui-contract'],
    serverHints: ['serveFile'],
  }),
  route({
    method: 'GET',
    route: '/app.js',
    group: 'static-app',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'static dir path containment',
    auditEvent: 'none',
    uiSurface: 'app shell',
    smokeCoverage: ['smoke:ui', 'smoke:ui-contract'],
    serverHints: ['serveFile'],
  }),
  route({
    method: 'GET',
    route: '/manifest.webmanifest',
    group: 'pwa',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'static manifest; no tokens',
    auditEvent: 'none',
    uiSurface: 'PWA install',
    smokeCoverage: ['smoke:pwa-cache'],
    serverHints: ['manifest.webmanifest'],
  }),
  route({
    method: 'GET',
    route: '/service-worker.js',
    group: 'pwa',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'static-only cache policy; sensitive routes bypassed',
    auditEvent: 'none',
    uiSurface: 'PWA install/offline shell',
    smokeCoverage: ['smoke:pwa-cache'],
    serverHints: ['service-worker.js'],
  }),
];
