// Route inventory data (chunk 5/7). Order is load-bearing.
import { route } from './_shared.js';

export const part5 = [
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/capacity/request',
    group: 'capacity',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'orchestrator within policy',
    validation: 'actor spoofing rejected; requested count/reason/tasks/cost-risk',
    auditEvent: 'capacity_request_created',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/server.test.js'],
    serverHints: ['requestCapacity'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/capacity/policy',
    group: 'capacity',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageCapacityPolicy',
    validation: 'actor spoofing rejected; capacity/spawn/idle/worktree mode allowlists',
    auditEvent: 'capacity_policy_updated',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/server.test.js'],
    serverHints: ['setCapacityPolicy'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/worktree-policy',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageCapacityPolicy',
    validation: 'actor spoofing rejected; worktreeMode allowlist isolated|shared; shared-mode warning returned',
    auditEvent: 'session_worktree_policy_updated',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/registry.test.js'],
    serverHints: ['setSessionWorktreePolicy'],
  }),
  route({
    method: 'GET',
    route: '/api/supervisor/overview',
    group: 'supervisor',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped supervisor.overview tool lease',
    validation: 'supervisor tool lease or operator auth; public-safe cross-project state summary',
    auditEvent: 'none',
    uiSurface: 'supervisor console',
    smokeCoverage: ['test/supervisor.test.js', 'test/supervisor-api.test.js'],
    serverHints: ['supervisorOverview'],
  }),
  route({
    method: 'POST',
    route: '/api/supervisor/resign',
    group: 'supervisor',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'medium',
    approval: 'self-revocation only',
    validation: 'requires supervisor tool lease; revokes only the caller lease id',
    auditEvent: 'agent_tool_lease_revoked',
    uiSurface: 'external supervisor MCP client',
    smokeCoverage: ['test/supervisor-api.test.js', 'smoke:mcp-supervisor-flow'],
    serverHints: ['revokeToolLease'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/orchestrator',
    group: 'orchestrator',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'session exists; returns server-owned conversation thread without raw lease tokens',
    auditEvent: 'none',
    uiSurface: 'session orchestrator console',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['getOrchestratorThread'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/orchestrator/messages',
    group: 'orchestrator',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'critical',
    approval: 'createLane',
    validation: 'actor spoofing rejected; message size bounded; executor/provider/workdir validation; scoped tool lease callers must be active orchestrator; spawned lane receives scoped tool lease',
    auditEvent: 'orchestrator_message_queued',
    uiSurface: 'session orchestrator console',
    smokeCoverage: ['test/server.test.js', 'smoke:ui-contract'],
    serverHints: ['sendOrchestratorMessage', 'createToolLease'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/orchestrator/enroll',
    group: 'orchestrator',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'caller identity derived from x-orca-tool-lease header only; takeover gated on stale/explicit',
    auditEvent: 'orchestrator_enrolled',
    uiSurface: 'session orchestrator console',
    smokeCoverage: ['test/orchestrator-enroll.test.js'],
    serverHints: ['enrollOrchestrator'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/orchestrator/resign',
    group: 'orchestrator',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'only the holder lease (or a dashboard operator) may resign; idempotent',
    auditEvent: 'orchestrator_resigned',
    uiSurface: 'session orchestrator console',
    smokeCoverage: ['test/orchestrator-enroll.test.js'],
    serverHints: ['resignOrchestrator'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/orchestrator/status',
    group: 'orchestrator',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped orchestrator.status tool lease',
    validation: 'session exists; scoped tool leases must validate against the session project/id; returns ownership + lane tree + backlog roll-up + next required tool',
    auditEvent: 'none',
    uiSurface: 'session orchestrator console',
    smokeCoverage: ['smoke:mcp-backlog-flow'],
    serverHints: ['orchestratorStatus'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/supervisor/audit',
    group: 'supervisor',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized supervisor/dashboard',
    validation: 'actor spoofing rejected; verdict allowlist accept|request_fix|block; findings bounded',
    auditEvent: 'session_supervisor_audited',
    uiSurface: 'supervisor console',
    smokeCoverage: ['test/supervisor.test.js', 'test/supervisor-api.test.js'],
    serverHints: ['recordSupervisorSessionAudit'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/tasks',
    group: 'task',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'session exists; optional state filter',
    auditEvent: 'none',
    uiSurface: 'session backlog',
    smokeCoverage: ['test/registry-tasks.test.js'],
    serverHints: ['listTasks'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/tasks',
    group: 'task',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'actor spoofing rejected; title required; executorType validated against supported types',
    auditEvent: 'task_added',
    uiSurface: 'session backlog',
    smokeCoverage: ['test/registry-tasks.test.js', 'smoke:mcp-backlog-flow'],
    serverHints: ['addTask'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/tasks/bulk',
    group: 'task',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'actor spoofing rejected; bounded array; 422 when none added',
    auditEvent: 'task_added',
    uiSurface: 'session backlog',
    smokeCoverage: ['smoke:mcp-backlog-flow'],
    serverHints: ['bulkAddTasks'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/backlog',
    group: 'backlog',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'session exists; returns counts, capacity, stall reasons, completion signal',
    auditEvent: 'none',
    uiSurface: 'session backlog',
    smokeCoverage: ['test/registry-tasks.test.js', 'smoke:mcp-backlog-flow'],
    serverHints: ['sessionBacklogStatus'],
  }),
  route({
    method: 'PATCH',
    route: '/api/tasks/{taskId}',
    group: 'task',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'lease scoped to the task\'s own session/project + active-orchestrator ownership enforced',
    auditEvent: 'task_state_changed',
    uiSurface: 'session backlog',
    smokeCoverage: ['test/registry-tasks.test.js'],
    serverHints: ['updateTask', 'assertOrchestratorOwnership'],
  }),
  route({
    method: 'DELETE',
    route: '/api/tasks/{taskId}',
    group: 'task',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'lease scoped to the task\'s own session/project + ownership; refuses assigned/in_lane tasks',
    auditEvent: 'task_deleted',
    uiSurface: 'session backlog',
    smokeCoverage: ['test/registry-tasks.test.js'],
    serverHints: ['deleteTask'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/capacity/requests/{requestId}/approve',
    group: 'capacity',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageCapacityPolicy',
    validation: 'actor spoofing rejected; request exists/pending',
    auditEvent: 'capacity_request_approved',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/server.test.js'],
    serverHints: ['approveCapacityRequest'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/capacity/requests/{requestId}/reject',
    group: 'capacity',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'manageCapacityPolicy',
    validation: 'actor spoofing rejected; request exists/pending',
    auditEvent: 'capacity_request_rejected',
    uiSurface: 'session settings/capacity',
    smokeCoverage: ['test/capacity.test.js', 'test/server.test.js'],
    serverHints: ['rejectCapacityRequest'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/lanes',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped session.describe tool lease',
    validation: 'session exists; scoped tool leases must validate against the session project/id',
    auditEvent: 'none',
    uiSurface: 'session/workflow',
    smokeCoverage: ['smoke:api', 'smoke:ui-inventory'],
    serverHints: ['listLanes'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/lanes',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'critical',
    approval: 'createLane',
    validation: 'actor spoofing rejected; executor/provider/workdir/MCP/tool/capacity validation',
    auditEvent: 'lane_created',
    uiSurface: 'session/workflow',
    smokeCoverage: ['test/registry.test.js', 'test/server.test.js', 'smoke:api'],
    serverHints: ['createLane'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/audit-done-lanes',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'auditDoneLanes',
    validation: 'actor spoofing rejected; session exists; eligible lanes only',
    auditEvent: 'session_audit_batch_queued',
    uiSurface: 'session/workflow audit queue',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['queueDoneLanesAudit'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/plan',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'session exists; actor spoofing rejected; goal/plan bounded',
    auditEvent: 'session_plan_updated',
    uiSurface: 'orchestrator console',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['updateSessionPlan'],
  }),
  route({
    method: 'POST',
    route: '/api/sessions/{sessionId}/attachments',
    group: 'sessions',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'session exists; actor spoofing rejected; base64 decoded; <=12MB; filename sanitized + path-contained',
    auditEvent: 'session_attachment_uploaded',
    uiSurface: 'orchestrator console composer',
    smokeCoverage: ['test/registry.test.js'],
    serverHints: ['saveSessionAttachment'],
  }),
  route({
    method: 'GET',
    route: '/api/sessions/{sessionId}/audit-events',
    group: 'audit',
    auth: 'none',
    mutationRisk: 'none',
    approval: 'none',
    validation: 'session exists; status query decoded',
    auditEvent: 'none',
    uiSurface: 'session/workflow audit queue',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ["parts[3] === 'audit-events'"],
  }),

  route({
    method: 'GET',
    route: '/api/lanes/{laneId}',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session_or_scoped_tool_lease',
    mutationRisk: 'none',
    approval: 'authorized operator or scoped lane.get tool lease',
    validation: 'lane exists; scoped tool leases must validate against the lane project/session/id',
    auditEvent: 'none',
    uiSurface: 'lane detail',
    smokeCoverage: ['smoke:ui-inventory'],
    serverHints: ["parts[1] === 'lanes'"],
  }),
  route({
    method: 'DELETE',
    route: '/api/lanes/{laneId}',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'medium',
    approval: 'none',
    validation: 'lane exists and is terminal (live lanes refused so a child is never orphaned)',
    auditEvent: 'lane_deleted',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/process-lifecycle-safety.test.js'],
    serverHints: ['deleteLane'],
  }),
  route({
    method: 'PATCH',
    route: '/api/lanes/{laneId}/controls',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'updateLaneControls',
    validation: 'actor spoofing rejected; model/mode/intelligence bounded and audited',
    auditEvent: 'lane_controls_updated',
    uiSurface: 'orchestrator/executor lane controls',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['updateLaneControls'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/stop',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'critical',
    approval: 'stopLane',
    validation: 'actor spoofing rejected; lane active/known process',
    auditEvent: 'lane_stopped',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/server.test.js'],
    serverHints: ['stopLane'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/retry',
    group: 'lanes',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'retryLane',
    validation: 'actor spoofing rejected; lane failed/stopped/fix_requested',
    auditEvent: 'lane_retried',
    uiSurface: 'lane detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['retryLane'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/audit',
    group: 'audit',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'auditLane',
    validation: 'actor spoofing rejected; critique gate satisfied; idempotent pending audit',
    auditEvent: 'lane_audit_queued',
    uiSurface: 'lane detail/audit queue',
    smokeCoverage: ['test/server.test.js', 'test/critique-audit.test.js'],
    serverHints: ['queueLaneAudit'],
  }),
  route({
    method: 'POST',
    route: '/api/lanes/{laneId}/critique/bundle',
    group: 'critique',
    auth: 'api_token_or_paired_browser_session',
    mutationRisk: 'high',
    approval: 'authorized executor/orchestrator/dashboard',
    validation: 'actor spoofing rejected; lane exists; nonce minted for current revision',
    auditEvent: 'critique_bundle_created',
    uiSurface: 'critique/self-check detail',
    smokeCoverage: ['test/critique-audit.test.js', 'test/critique-audit-api.test.js'],
    serverHints: ['createCritiqueBundle'],
  }),
];
