// Default provider profiles + per-kind profile factory. Extracted from
// provider-profiles.js.

import { ROLE_COMPATIBILITY, nowIso } from './constants.js';
import { normalizeStringArray } from './validation.js';

export function apiProfile({
  id,
  displayName,
  baseUrl,
  apiStyle,
  secretRef,
  apiKeyEnv,
  enabled = false,
}) {
  return {
    id,
    displayName,
    kind: 'api',
    enabled,
    roleCompatibility: [...ROLE_COMPATIBILITY],
    defaultModel: '',
    allowedModels: [],
    defaultArgs: [],
    permissionsProfile: 'restricted',
    mcpScopes: ['api', 'all'],
    workdirRoots: [],
    defaultWorkingDir: '',
    envWhitelist: [],
    maxConcurrentLanes: 4,
    healthCheck: { type: 'api-config' },
    installPolicy: 'plan_only',
    updatePolicy: 'notify_only',
    baseUrl,
    apiStyle,
    secretRef,
    apiKeyEnv,
    timeoutMs: 30000,
    retryPolicy: { retries: 1, backoffMs: 500 },
    streaming: true,
    requestTemplate: 'chat-completions-compatible',
    responseParser: 'chat-completions-compatible',
    redactionPolicy: 'redact-authorization-and-body-secrets',
  };
}

export function defaultProfiles() {
  const cwd = process.cwd();
  return {
    codex: {
      id: 'codex',
      displayName: 'Codex',
      kind: 'codex',
      enabled: true,
      roleCompatibility: [...ROLE_COMPATIBILITY],
      defaultModel: process.env.ORCA_CODEX_MODEL || '',
      allowedModels: normalizeStringArray(process.env.ORCA_CODEX_MODELS?.split(','), [], 32),
      defaultArgs: [],
      permissionsProfile: 'per-lane',
      mcpScopes: ['codex', 'all'],
      workdirRoots: [cwd],
      defaultWorkingDir: cwd,
      envWhitelist: ['PATH', 'HOME', 'TMPDIR', 'LANG', 'LC_ALL', 'LC_CTYPE', 'USER', 'SHELL', 'TERM'],
      maxConcurrentLanes: 2,
      healthCheck: { type: 'cli-version', command: ['codex', '--version'] },
      installPolicy: 'plan_only',
      updatePolicy: 'notify_only',
      binary: process.env.ORCA_CODEX_BINARY || 'codex',
      allowedBinaries: normalizeStringArray([process.env.ORCA_CODEX_BINARY || 'codex', 'codex']),
      officialSourcePolicy: 'openai/codex or @openai/codex only',
      secretRef: null,
      apiKeyEnv: null,
    },
    claude: {
      id: 'claude',
      displayName: 'Claude',
      kind: 'claude',
      enabled: true,
      roleCompatibility: [...ROLE_COMPATIBILITY],
      defaultModel: process.env.ORCA_CLAUDE_MODEL || '',
      allowedModels: normalizeStringArray(process.env.ORCA_CLAUDE_MODELS?.split(','), [], 32),
      defaultArgs: [],
      permissionsProfile: 'per-lane',
      mcpScopes: ['claude', 'all'],
      workdirRoots: [cwd],
      defaultWorkingDir: cwd,
      envWhitelist: ['PATH', 'HOME', 'TMPDIR', 'LANG', 'LC_ALL', 'LC_CTYPE', 'USER', 'SHELL', 'TERM'],
      maxConcurrentLanes: 2,
      healthCheck: { type: 'cli-version', command: ['claude', '--version'] },
      installPolicy: 'plan_only',
      updatePolicy: 'notify_only',
      binary: process.env.ORCA_CLAUDE_BINARY || 'claude',
      allowedBinaries: normalizeStringArray([process.env.ORCA_CLAUDE_BINARY || 'claude', 'claude']),
      officialSourcePolicy: 'anthropic/claude-code or @anthropic/claude-code only',
      secretRef: null,
      apiKeyEnv: null,
    },
    'gemini-cli': {
      id: 'gemini-cli',
      displayName: 'Gemini CLI',
      kind: 'cli',
      enabled: true,
      roleCompatibility: [...ROLE_COMPATIBILITY],
      defaultModel: process.env.ORCA_GEMINI_CLI_MODEL || '',
      allowedModels: normalizeStringArray(process.env.ORCA_GEMINI_CLI_MODELS?.split(','), [], 32),
      defaultArgs: normalizeStringArray((process.env.ORCA_GEMINI_CLI_DEFAULT_ARGS || '').split(/\s+/), [], 64),
      permissionsProfile: 'per-lane',
      mcpScopes: ['gemini-cli', 'all'],
      workdirRoots: normalizeStringArray((process.env.ORCA_GEMINI_CLI_WORKDIR_ROOTS || cwd).split(','), [cwd], 32),
      defaultWorkingDir: cwd,
      envWhitelist: normalizeStringArray((process.env.ORCA_GEMINI_CLI_ENV_WHITELIST || 'PATH,HOME,TMPDIR,LANG,LC_ALL,LC_CTYPE,USER,SHELL,TERM').split(','), [], 64),
      maxConcurrentLanes: 2,
      healthCheck: { type: 'cli-version', command: [process.env.ORCA_GEMINI_CLI_BINARY || 'gemini', '--version'] },
      installPolicy: 'plan_only',
      updatePolicy: 'notify_only',
      binary: process.env.ORCA_GEMINI_CLI_BINARY || 'gemini',
      allowedBinaries: normalizeStringArray((process.env.ORCA_GEMINI_CLI_ALLOWED_BINARIES || process.env.ORCA_GEMINI_CLI_BINARY || 'gemini').split(','), ['gemini'], 32),
      officialSourcePolicy: 'google-gemini/gemini-cli or @google/gemini-cli only',
      secretRef: null,
      apiKeyEnv: null,
    },
    'composer-cli': {
      id: 'composer-cli',
      displayName: 'Composer CLI',
      kind: 'cli',
      enabled: true,
      roleCompatibility: [...ROLE_COMPATIBILITY],
      defaultModel: process.env.ORCA_COMPOSER_CLI_MODEL || '',
      allowedModels: normalizeStringArray(process.env.ORCA_COMPOSER_CLI_MODELS?.split(','), [], 32),
      defaultArgs: normalizeStringArray((process.env.ORCA_COMPOSER_CLI_DEFAULT_ARGS || '').split(/\s+/), [], 64),
      permissionsProfile: 'per-lane',
      mcpScopes: ['composer-cli', 'all'],
      workdirRoots: normalizeStringArray((process.env.ORCA_COMPOSER_CLI_WORKDIR_ROOTS || cwd).split(','), [cwd], 32),
      defaultWorkingDir: cwd,
      envWhitelist: normalizeStringArray((process.env.ORCA_COMPOSER_CLI_ENV_WHITELIST || 'PATH,HOME,TMPDIR,LANG,LC_ALL,LC_CTYPE,USER,SHELL,TERM').split(','), [], 64),
      maxConcurrentLanes: 2,
      healthCheck: { type: 'cli-version', command: [process.env.ORCA_COMPOSER_CLI_BINARY || 'cursor-agent', '--version'] },
      installPolicy: 'plan_only',
      updatePolicy: 'notify_only',
      binary: process.env.ORCA_COMPOSER_CLI_BINARY || 'cursor-agent',
      allowedBinaries: normalizeStringArray((process.env.ORCA_COMPOSER_CLI_ALLOWED_BINARIES || process.env.ORCA_COMPOSER_CLI_BINARY || 'cursor-agent').split(','), ['cursor-agent'], 32),
      officialSourcePolicy: 'Cursor Agent CLI only; defaults to cursor-agent',
      secretRef: null,
      apiKeyEnv: null,
    },
    'custom-cli': {
      id: 'custom-cli',
      displayName: 'Custom CLI',
      kind: 'cli',
      enabled: Boolean(process.env.ORCA_ENABLE_CUSTOM_CLI === 'true' || process.env.ORCA_CLI_BINARY),
      roleCompatibility: [...ROLE_COMPATIBILITY],
      defaultModel: '',
      allowedModels: [],
      defaultArgs: normalizeStringArray((process.env.ORCA_CLI_DEFAULT_ARGS || '').split(/\s+/), [], 64),
      permissionsProfile: 'restricted',
      mcpScopes: ['cli', 'all'],
      workdirRoots: normalizeStringArray((process.env.ORCA_CLI_WORKDIR_ROOTS || cwd).split(','), [cwd], 32),
      defaultWorkingDir: cwd,
      envWhitelist: normalizeStringArray((process.env.ORCA_CLI_ENV_WHITELIST || 'PATH,HOME,TMPDIR,LANG,LC_ALL,LC_CTYPE,USER,SHELL,TERM').split(','), [], 64),
      maxConcurrentLanes: 1,
      healthCheck: { type: 'cli-version', command: [process.env.ORCA_CLI_BINARY || 'node', '--version'] },
      installPolicy: 'plan_only',
      updatePolicy: 'notify_only',
      binary: process.env.ORCA_CLI_BINARY || 'node',
      allowedBinaries: normalizeStringArray((process.env.ORCA_CLI_ALLOWED_BINARIES || process.env.ORCA_CLI_BINARY || 'node').split(','), ['node'], 32),
      officialSourcePolicy: 'user-configured allowlist only',
      secretRef: null,
      apiKeyEnv: null,
    },
    'openai-compatible': apiProfile({
      id: 'openai-compatible',
      displayName: 'OpenAI-compatible API',
      baseUrl: 'https://api.openai.com/v1',
      apiStyle: 'openai-compatible',
      secretRef: 'provider:openai-compatible',
      apiKeyEnv: 'ORCA_OPENAI_COMPATIBLE_API_KEY',
    }),
    gemini: apiProfile({
      id: 'gemini',
      displayName: 'Gemini API',
      baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
      apiStyle: 'gemini',
      secretRef: 'provider:gemini',
      apiKeyEnv: 'ORCA_GEMINI_API_KEY',
    }),
    kimi: apiProfile({
      id: 'kimi',
      displayName: 'Kimi API',
      baseUrl: 'https://api.moonshot.ai/v1',
      apiStyle: 'openai-compatible',
      secretRef: 'provider:kimi',
      apiKeyEnv: 'ORCA_KIMI_API_KEY',
    }),
    deepseek: apiProfile({
      id: 'deepseek',
      displayName: 'DeepSeek API',
      baseUrl: 'https://api.deepseek.com/v1',
      apiStyle: 'openai-compatible',
      secretRef: 'provider:deepseek',
      apiKeyEnv: 'ORCA_DEEPSEEK_API_KEY',
    }),
    openrouter: apiProfile({
      id: 'openrouter',
      displayName: 'OpenRouter API',
      baseUrl: 'https://openrouter.ai/api/v1',
      apiStyle: 'openai-compatible',
      secretRef: 'provider:openrouter',
      apiKeyEnv: 'ORCA_OPENROUTER_API_KEY',
    }),
    composer: apiProfile({
      id: 'composer',
      displayName: 'Composer',
      baseUrl: 'http://127.0.0.1:3000',
      apiStyle: 'openai-compatible',
      secretRef: 'provider:composer',
      apiKeyEnv: 'ORCA_COMPOSER_API_KEY',
      enabled: false,
    }),
  };
}

